### ISSUE TITLE
报错是为啥呢

### ISSUE THREAD

**Issue by monobo1989** [JDDKCN/SMSBoomGUI#1]
20:13:42,005 [ERROR] ThreadPoolExecutor-0_37 req:72 - 请求失败_ssl.c:1108: The handshake operation timed out
❌  20:13:44,900 [ERROR] ThreadPoolExecutor-0_29 req:72 - 请求失败timed out

请问总出现报错是为啥？而且电脑总是咚咚的叫啊

**Comment by JDDKCN** [comment]
这个是API的问题，请求超时什么的。那么多API总不可能存活率100%吧，所以出现这个很正常，可以忽略喵~
至于电脑响提示音什么的，可以去SMSBoom本家问一下，咱这里只是给做了GUI哈哈哈

**Comment by monobo1989** [comment]
好滴，如果能关闭报错提示音就行了。
谢谢啦，这个GUI很方便，不需要输入那些代码。
